# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'masterChange.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MasterChange(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(350, 400)
        MainWindow.setStyleSheet("background-color: rgb(36, 36, 36);\n"
"color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 30, 191, 16))
        self.label.setObjectName("label")
        self.keyOld = QtWidgets.QLineEdit(self.centralwidget)
        self.keyOld.setGeometry(QtCore.QRect(30, 70, 281, 20))
        self.keyOld.setObjectName("keyOld")
        self.keyNew1 = QtWidgets.QLineEdit(self.centralwidget)
        self.keyNew1.setGeometry(QtCore.QRect(30, 150, 281, 20))
        self.keyNew1.setObjectName("keyNew1")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 110, 191, 16))
        self.label_2.setObjectName("label_2")
        self.keyNew2 = QtWidgets.QLineEdit(self.centralwidget)
        self.keyNew2.setGeometry(QtCore.QRect(30, 230, 281, 20))
        self.keyNew2.setText("")
        self.keyNew2.setObjectName("keyNew2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 190, 181, 16))
        self.label_3.setObjectName("label_3")
        self.errLabel = QtWidgets.QLabel(self.centralwidget)
        self.errLabel.setGeometry(QtCore.QRect(20, 310, 291, 16))
        self.errLabel.setText("")
        self.errLabel.setObjectName("errLabel")
        self.changeButton = QtWidgets.QPushButton(self.centralwidget)
        self.changeButton.setGeometry(QtCore.QRect(230, 270, 75, 23))
        self.changeButton.setObjectName("changeButton")
        self.hideBtn = QtWidgets.QPushButton(self.centralwidget)
        self.hideBtn.setGeometry(QtCore.QRect(140, 270, 75, 23))
        self.hideBtn.setObjectName("hideBtn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 350, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Введите ваш старый мастер ключ:"))
        self.label_2.setText(_translate("MainWindow", "Введите ваш новый мастер ключ:"))
        self.label_3.setText(_translate("MainWindow", "Введите ваш новый мастер ключ:"))
        self.changeButton.setText(_translate("MainWindow", "Сменить"))
        self.hideBtn.setText(_translate("MainWindow", "Показать"))
