# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWind.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, P1QtPass):
        P1QtPass.setObjectName("P1QtPass")
        P1QtPass.resize(800, 500)
        P1QtPass.setStyleSheet("background-color: rgb(36, 36, 36);\n"
"color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(P1QtPass)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(20, 40, 751, 231))
        self.tableWidget.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.databaseInfo = QtWidgets.QTextBrowser(self.centralwidget)
        self.databaseInfo.setGeometry(QtCore.QRect(20, 280, 751, 141))
        self.databaseInfo.setObjectName("databaseInfo")
        self.searchName = QtWidgets.QLineEdit(self.centralwidget)
        self.searchName.setGeometry(QtCore.QRect(470, 10, 301, 21))
        self.searchName.setObjectName("searchName")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(180, 10, 281, 21))
        self.label.setObjectName("label")
        self.addBtn = QtWidgets.QPushButton(self.centralwidget)
        self.addBtn.setGeometry(QtCore.QRect(20, 10, 151, 23))
        self.addBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.addBtn.setStyleSheet("font: 63 8pt \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255)")
        self.addBtn.setObjectName("addBtn")
        self.changeMaster = QtWidgets.QPushButton(self.centralwidget)
        self.changeMaster.setGeometry(QtCore.QRect(20, 430, 131, 23))
        self.changeMaster.setObjectName("changeMaster")
        P1QtPass.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(P1QtPass)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setItalic(True)
        self.menuFile.setFont(font)
        self.menuFile.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.menuFile.setObjectName("menuFile")
        P1QtPass.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(P1QtPass)
        self.statusbar.setObjectName("statusbar")
        P1QtPass.setStatusBar(self.statusbar)
        self.exportBtn = QtWidgets.QAction(P1QtPass)
        font = QtGui.QFont()
        font.setKerning(False)
        self.exportBtn.setFont(font)
        self.exportBtn.setObjectName("exportBtn")
        self.importBtn = QtWidgets.QAction(P1QtPass)
        font = QtGui.QFont()
        font.setKerning(False)
        self.importBtn.setFont(font)
        self.importBtn.setObjectName("importBtn")
        self.menuFile.addAction(self.exportBtn)
        self.menuFile.addAction(self.importBtn)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(P1QtPass)
        QtCore.QMetaObject.connectSlotsByName(P1QtPass)

    def retranslateUi(self, P1QtPass):
        _translate = QtCore.QCoreApplication.translate
        P1QtPass.setWindowTitle(_translate("P1QtPass", "MainWindow"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("P1QtPass", "Название"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("P1QtPass", "Логин"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("P1QtPass", "URL"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("P1QtPass", "Описание"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("P1QtPass", "uniqueID"))
        self.label.setText(_translate("P1QtPass", " Название или ключевое слово поиска:"))
        self.addBtn.setText(_translate("P1QtPass", "Добавить пароль"))
        self.changeMaster.setText(_translate("P1QtPass", "Изменить мастер ключ"))
        self.menuFile.setTitle(_translate("P1QtPass", "Файл"))
        self.exportBtn.setText(_translate("P1QtPass", "Экспорт"))
        self.importBtn.setText(_translate("P1QtPass", "Импорт"))
