# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'welcomeWind.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LogWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 500)
        MainWindow.setStyleSheet("background-color: rgb(36, 36, 36);\n"
"color: rgb(255, 255, 255);\n"
"font: 63 8pt \"Yu Gothic UI Semibold\";")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 40, 251, 41))
        self.label.setStyleSheet("font: 63 8pt \"Yu Gothic UI Semibold\";\n"
"color: rgb(255, 255, 255)")
        self.label.setObjectName("label")
        self.errLine = QtWidgets.QLabel(self.centralwidget)
        self.errLine.setGeometry(QtCore.QRect(70, 90, 631, 16))
        self.errLine.setStyleSheet("color: rgb(255, 255, 255);")
        self.errLine.setText("")
        self.errLine.setObjectName("errLine")
        self.interaction_container = QtWidgets.QGroupBox(self.centralwidget)
        self.interaction_container.setGeometry(QtCore.QRect(110, 120, 581, 191))
        self.interaction_container.setStyleSheet("background-color: rgb(48, 48, 48);")
        self.interaction_container.setTitle("")
        self.interaction_container.setObjectName("interaction_container")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.interaction_container)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(340, 90, 211, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.unlockBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.unlockBtn.setFont(font)
        self.unlockBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.unlockBtn.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"font: 63 8pt \"Yu Gothic UI Semibold\";\n"
"color: rgb(255, 255, 255)")
        self.unlockBtn.setObjectName("unlockBtn")
        self.horizontalLayout.addWidget(self.unlockBtn)
        self.closeBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.closeBtn.setFont(font)
        self.closeBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.closeBtn.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"font: 63 8pt \"Yu Gothic UI Semibold\";\n"
"color: rgb(255, 255, 255)")
        self.closeBtn.setObjectName("closeBtn")
        self.horizontalLayout.addWidget(self.closeBtn)
        self.label_2 = QtWidgets.QLabel(self.interaction_container)
        self.label_2.setGeometry(QtCore.QRect(50, 20, 211, 20))
        self.label_2.setStyleSheet("font: 63 8pt \"Yu Gothic UI Semibold\";\n"
"color: rgb(255, 255, 255)")
        self.label_2.setObjectName("label_2")
        self.masterKey = QtWidgets.QLineEdit(self.interaction_container)
        self.masterKey.setGeometry(QtCore.QRect(50, 50, 431, 20))
        self.masterKey.setMinimumSize(QtCore.QSize(133, 0))
        self.masterKey.setStyleSheet("color: rgb(255, 255, 255);")
        self.masterKey.setObjectName("masterKey")
        self.hideBtn = QtWidgets.QPushButton(self.interaction_container)
        self.hideBtn.setGeometry(QtCore.QRect(490, 50, 61, 23))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.hideBtn.setFont(font)
        self.hideBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.hideBtn.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"font: 63 8pt \"Yu Gothic UI Semibold\";\n"
"color: rgb(255, 255, 255)")
        self.hideBtn.setObjectName("hideBtn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.RightToolBarArea, self.toolBar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 19))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.menuFile.setFont(font)
        self.menuFile.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.exportBtn = QtWidgets.QAction(MainWindow)
        self.exportBtn.setObjectName("exportBtn")
        self.importBtn = QtWidgets.QAction(MainWindow)
        self.importBtn.setObjectName("importBtn")
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.exportBtn)
        self.menuFile.addAction(self.importBtn)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Менеджер паролей P1QtPass приветствует Вас!"))
        self.unlockBtn.setText(_translate("MainWindow", "Открыть хранилище"))
        self.closeBtn.setText(_translate("MainWindow", "Закрыть"))
        self.label_2.setText(_translate("MainWindow", "Пожалуйста, введите Ваш мастер-ключ:"))
        self.hideBtn.setText(_translate("MainWindow", "Спрятать"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.menuFile.setTitle(_translate("MainWindow", "Файл"))
        self.exportBtn.setText(_translate("MainWindow", "Экспорт"))
        self.importBtn.setText(_translate("MainWindow", "Импорт"))
